[package]
org = "ballerinai"
name = "remote.management"
version = "1.0.0"
distribution = "2201.9.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
path = "../native/build/libs/remote.management-native-1.0.0-SNAPSHOT.jar"
